<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComNetworkingHttpClient>true</BuiltInComNetworkingHttpClient>
    <RootNamespace>QueueWave</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia"                   Version="11.*" />
    <PackageReference Include="Avalonia.Desktop"           Version="11.*" />
    <PackageReference Include="Avalonia.Themes.Fluent"     Version="11.*" />
    <PackageReference Include="Avalonia.ReactiveUI"        Version="11.*" />
    <PackageReference Include="LibVLCSharp"                Version="3.*" />
    <PackageReference Include="LibVLCSharp.Avalonia"       Version="3.*" />
    <PackageReference Include="VideoLAN.LibVLC.Windows"    Version="3.*"
                      Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <PackageReference Include="CommunityToolkit.Mvvm"      Version="8.*" />
  </ItemGroup>
</Project>